### PR TITLE
Hibernate 5.2 compatiblity

### PR DESCRIPTION
**Pull request by mayjak**
I needed hibernate 5.2 compatibility right away for one of my projects. Here are the changes I had to make to get usertype working.
Fixes issue #56

### CODE REVIEW

**Comment by ceefour** [comment]
Thank you @mayjak .

Please support Hibernate 5.2. Spring Framework 4.3 and Spring Boot 1.4.0 already supports Hibernate 5.2.

**Comment by ptahchiev** [comment]
+1 on this one. There is a pull-request. What more do we need?

**Comment by davidkarlsen** [comment]
ping

**Comment by chrisphe** [comment]
Will be looking at this shortly

**Pull request closed without merging**
